//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AACOA
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoSotrudnik
    {
        public int id { get; set; }
        public Nullable<int> roleId { get; set; }
        public Nullable<int> eventId { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Role Role { get; set; }
    }
}
