//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AACOA
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogIn
    {
        public int id { get; set; }
        public int number { get; set; }
        public int password { get; set; }
    }
}
